spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biday
    username: root
    password: biday

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

payments:
  toss:
    secret:
      key: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6

  level:
    org.springframework.security: DEBUG
#org.springframework.web: DEBUG
#org.springframework.web.servlet: DEBUG
#org.springframework.web.filter: DEBUG